server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    database: 0
    port: 6379
    password: # by default, password is blank
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    connect-timeout: 3000ms
  main:
    allow-circular-references: true

# customized redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

# customized JWT
jwt:
  tokenHeader: Authorization
  secret: mySecret   # key
  expiration: 604800
  tokenHead: Bearer

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


secure:
  ignored:
    urls:
      - /*.html
      - /favicon.ico
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /swagger-ui/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /admin/login
      - /admin/register
