server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: 123456
    # publisher-confirms: true (deprecated)
    publisher-confirm-type: correlated
  main:
    allow-circular-references: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
